// This file is automatically generated. Do not modify it.
export const firebaseConfig = {
  "apiKey": "AIzaSyAiTQyk9upJiRkGSviTqGCUncKUE3swDys",
  "authDomain": "edugate-smk-92759.firebaseapp.com",
  "projectId": "edugate-smk-92759",
  "storageBucket": "edugate-smk-92759.appspot.com",
  "messagingSenderId": "104938216744",
  "appId": "1:104938216744:web:8e1d5e5b6a7c3d4e5f6a7b"
};
